# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0261976171c65bd6a02204fea43ca34847b33e5e40f5f97f560490cdc67358854a812bade238d36742c9d0921630dd66f3df5cf762a2dab38c38fe3bb41f7341

test:
  secret_key_base: 0460db556b4ff102a56a3ad6adb7e52567d7acf69321dfdc0cdf50db8bdec77e4ba5e71fc5fd9755b3c4ade1c43ff7ee9cf78ed18c120a49e4e90191ba32d576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
